### ISSUE TITLE
Keep GitHub's version udpated

### ISSUE THREAD

**Issue by oviliz** [moosend/website-tracking-modules-magento#8]
The latest version here is 1.0.5 while the one on the marketplace is 1.0.7, https://marketplace.magento.com/moosend-module-mootracker.html
Could you please keep the two in sync for those who want installing via composer instead?

**Comment by gentgaashi** [comment]
Hi, it is 1.0.7 here as well. It has not been tagged properly. Will be fixed.

**Comment by gentsp** [comment]
Hi Cristian,

The latest release has been tagged now with 1.0.7 in sync with the marketplace version.

Thank you for reporting :)
